name: Deploy and run on DG

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to DG
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: "dg"
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync (prod.)
        run: rsync -avz ~/work/blazify.tech/blazify.tech/ ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:/root/blazify.tech
      - name: Executing remote ssh commands using ssh key (prod.)
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          script: |
            cd /root/blazify.tech
            npm i
            npm run build
            pm2 delete blazify
            pm2 start 'serve -s build' --name blazify
            pm2 save
